apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 2
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apche
        image: apache:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service 
metadata:
  name: apache-service
spec: 
  type: ClusterIP
  selector:
    app: apache
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81

